config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'
  require 'sidekiq/web'
  
  mount Sidekiq::Web, at: '/admin/jobs'
  

  devise_for :users
  
  get 'pages/index'

  root 'pages#index'
  
  resources :appointments do
    member do
      patch 'accept_invite'
    end
  end
  
  post 'twilio/voice' => 'twilio#voice'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  has_many :invitations, :dependent => :destroy
  has_many :reminders
  
  accepts_nested_attributes_for :invitations, reject_if: proc { |attributes| attributes[:invite_email].blank? }, allow_destroy: true
  accepts_nested_attributes_for :reminders
  
  validates :title, :location, :time, presence: true
  validates_uniqueness_of :title, :scope => [:location, :description, :time], message: "This exact appointment already exists"
    

  private
    
  #For Create. Only passes if the friend's email is in the CheckMark database and passes its relationship by add current_user.id
  def self.invite_success?(appointment,current_user)
    bool_check=true
    appointment.reminders.each do |accept|
      accept.user_id = current_user.id
    end
    
    appointment.invitations.each do |invite|
      email_downcase=invite.invite_email.downcase
      
      if email_downcase != current_user.email
        if User.email_exist(email_downcase)
          invite.user_id=current_user.id
        else
          bool_check=false
        end
      else
        bool_check=false
      end
    end
    bool_check
  end
  
  #for update. Checks if friend's email exist in the CheckMark database. To delete a friend, add the word 'delete'
  def self.update_success?(edit_appointment,current_user)
    bool_check=true
    edit_appointment.invitations.each do |invite|
      email_downcase=invite.invite_email.downcase
      
      if User.email_exist(email_downcase) && email_downcase != current_user.email || invite.invite_email.downcase === 'delete'
        invite.update_attributes(user_id: current_user.id)
      else
        Invitation.where(invite_email: invite.invite_email).destroy_all
          
        bool_check=false
      end
    end
    bool_check
  end
  
  #Sidekiq for setting up reminders base on user options
  def self.set_reminder(user_id,appointment_id)
    appointment=Appointment.find(appointment_id)
    
    self.find(appointment_id).reminders.each do |option|
      if option.phone_sms_accept === true
        SmsWorker.perform_at(appointment.time,user_id,appointment_id)
      end
      if option.email_accept === true
        ReminderMailer.delay_until(appointment.time).send_email_reminder(user_id, appointment_id)
      end
      if option.phone_number_accept === true
        PhoneWorker.perform_at(appointment.time,user_id,appointment_id)
      end
    end
  end
end
  
 
  
   

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  
  #Displays the appointments for both invited and personal appointments
  def index
    @user_appointments=current_user.appointments.order(created_at: :desc)
    @invited_appointment=Appointment.joins(:invitations).where('invitations.invite_email' => current_user.email)
  end

  #Allow users to create an appointment
  def new
    @appointment=Appointment.new
    @appointment.reminders.build
    @appointment.invitations.build
  end
  
  #Parameters are sent and enters data into its respective model tables
  def create
    @appointment=current_user.appointments.new(appointment_params)
    
    if Appointment.invite_success?(@appointment,current_user) && @appointment.save
      #Sets the time for reminders
      Appointment.set_reminder(current_user.id,@appointment.id)
      
      flash[:success] = "You successfully created your appointment"
      redirect_to action: :index
    else
      flash[:emailerror]="If you are inviting others, double check that the email is associated with CheckMark and your own email is not included in the list"
      flash[:error] = "Your appointment was not saved"
      
      @appointment.invitations.build if @appointment.invitations.blank?
      
      render "new"
    end
  end
  
  #Allow users to edit their personal appointments
  def edit
    @edit_appointment=Appointment.find(params[:id])
    @edit_appointment.invitations.build
  end
  
   #Parameters are sent and updated
   def update
     @edit_appointment=Appointment.find(params[:id])
     
      if @edit_appointment.update(appointment_params)
        if !Appointment.update_success?(@edit_appointment,current_user)
        flash[:emailerror]="Your friend's email is not associated with CheckMark and make sure not to place your email in the friend's list."
        return redirect_to  action: :edit
        end
        #Sets the time for reminders
        Appointment.set_reminder(current_user.id,@edit_appointment.id)
        
        flash[:success] = "You successfully updated your appointment"
        return redirect_to action: :index
      else
       flash[:error] = "Your appointment was not saved"
       
        @edit_appointment.invitations.build if @edit_appointment.invitations.blank?
        
        render "edit"
      end
  end
  
  #Delete and appointment and prompts user, "Are you sure?"
  def destroy
    if Appointment.destroy(params[:id])
      flash[:success] = "You successfully deleted your appointment"
      redirect_to action: :index
    else
      flash[:error] = "There was a problem deleting your appointment"
      redirect_to action: :index
    end
  end
  
  #PATCH to allow attendees to accept an invitation
  def accept_invite
    @accept=Invitation.find(params[:id])
    
    #accepts invitation and updates invitation to True
    Invitation.accept_invite(@accept,current_user)
    
    #Sets the time for reminders
    Appointment.set_reminder(current_user.id,@accept.appointment_id)
    
    flash[:success] = "Appointment accepted"
    redirect_to action: :index
  end
  


  private
  
  def appointment_params
    params.require(:appointment).permit(:title,:description,:location,:time, invitations_attributes:[:id,:invite_email,:accept, :_destroy],
    reminders_attributes:[:id, :email_accept, :phone_number_accept, :phone_sms_accept, :appointment_id, :user_id, :_destroy])
  end
end

app/views/appointments/_form_edit.html.erb
<p>**To remove an email from the list, replace the email with the word 'delete'</p>

<%= simple_form_for @edit_appointment do |f| %>
<%= f.input :title, placeholder: 'your title of appointment goes here' %>
<%= f.input :location, placeholder: 'your appointment location goes here' %>
<%= f.input :description, placeholder: 'optional description goes here' %>
<%= f.input :time, placeholder: 'time of appointment goes here' %>

<%=f.fields_for :reminders do |reminder| %>
<%=reminder.label :email_accept, "Remind via email" %>
<%=reminder.check_box :email_accept %>
<%=reminder.label :phone_number_accept, "Remind via phone number" %>
<%=reminder.check_box :phone_number_accept %>
<%=reminder.label :phone_sms_accept, "Remind via text message" %>
<%=reminder.check_box :phone_sms_accept %>
<% end %>

<%= f.fields_for :invitations do |builder| %>
<div class="emailF">
  <p class="fields first_field">
  <%= builder.label :invite_email, "**Friend email" %>
  <%= builder.email_field :invite_email %>
  <%=builder.hidden_field :accept, :value => 'f' %>
  </p>
<% end %>
</div>
<a class="add" href="javascript:void(0)">Add Email field</a>

<%= f.button :submit %>
<% end %>

app/views/appointments/_form_new.html.erb
<%= simple_form_for @appointment do |f| %>
<%= f.input :title, placeholder: 'your title of appointment goes here' %>
<%= f.input :location, placeholder: 'your appointment location goes here' %>
<%= f.input :description, placeholder: 'optional description goes here' %>
<%= f.input :time, placeholder: 'time of appointment goes here' %>

<%=f.fields_for :reminders do |reminder| %>
<%=reminder.label :email_accept, "Remind via email" %>
<%=reminder.check_box :email_accept %>
<%=reminder.label :phone_number_accept, "Remind via phone number" %>
<%=reminder.check_box :phone_number_accept %>
<%=reminder.label :phone_sms_accept, "Remind via text message" %>
<%=reminder.check_box :phone_sms_accept %>
<% end %>

<%= f.fields_for :invitations do |builder| %>
<div class="emailF">
  <p class="fields first_field">
  <%= builder.label :invite_email, "Invite your local CheckMark friend" %>
  <%= builder.email_field :invite_email %>
  <%=builder.hidden_field :accept, :value => 'f' %>
  <%= builder.hidden_field :_destroy %>
  <a class="remove" href="javascript:void(0)">Remove Email</a>
  </p>
</div>
<% end %>

<a class="add" href="javascript:void(0)">Add Email field</a>

<%= f.button :submit %>
<% end %>

app/views/appointments/edit.html.erb
<div class="flash-message-error">
  <p class="error">
    <%= flash[:error] %>
  </p>
  <p class="error">
    <%= flash[:emailerror] %>
  </p>
</div>
<h2 class="title">
  Edit this appointment
</h2>
<div class="container edit-current">
  <div class="row">
    <div class="form-errors">
      <% if @edit_appointment.errors.any? %>
      <p><%= pluralize(@edit_appointment.errors.count, "error") %> prohibited this post from being saved:</p>
      <ul class="error-msgs">
         <% @edit_appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      </ul>
    </div>
        <% end %>
      <% end %>
      
    <div class="edit-appointment">
     <%= render partial: 'form_edit' %>
    </div>
  </div>
</div>

app/views/appointments/index.html.erb
<div class="flash-message-success"><p class="success"><%= flash[:success] %></p></div>
<div class="flash-message-success"><p class="success"><%= flash[:email] %></p></div>
<div class="flash-message-success"><p class="success"><%= flash[:phone] %></p></div>
<div class="flash-message-success"><p class="success"><%= flash[:sms] %></p></div>
<div class="flash-message-error"><p class="error"><%= flash[:error] %></p></div>
<h2 class="title">Your Appointments List</h2>
<div class="container">
  <div class="row">
    <div class="invitations">
      <h3 class="CheckMark_lists">Your CheckMark friends' invitations </h3>
      <p> You have <%=Invitation.where(:invite_email => current_user.email).count %> total invitation(s):</p>
      <%if Invitation.where(:invite_email => current_user.email).count != 0 %> 
        <% @invited_appointment.each do |appointment| %>
      <section class="box-invite">
        <p class="TitleOfAppointment"><span>Title of Appointment/Event:</span> <%= appointment.title %></p>
        <p><span>Location:</span> <%= appointment.location %> </p>
        <p><span>Description:</span> <%= appointment.description %></p>
        <p><span>Time:</span> <%= appointment.time %> </p>
            <%if appointment.time < DateTime.now %>
        <p style="color:red;">this appointment has passed</p>
            <% end %>
          <% appointment.invitations.where(:invite_email => current_user.email).each do |inviter| %>
        <p class="user_email">Invited by:<span> <%= User.find_by(:id => inviter.user_id).email %></span> </p>
            <% if inviter.accept == false %>
        <p class="queue-msg">You have not accepted this invitation yet. Accept for an email reminder!</p>
              <%= link_to "Accept", accept_invite_appointment_path(inviter),:method => :patch, class: "accept" %>
      </section>
            <% else %>
      <p class="queued-msg">You have queued for an email reminder for this appointment</p>
            <% end %>
      </section>
         <% end %>
      <% end %>
  <% else %>
  <p>No friendly appointments at this time </p>
  <% end %>
  </div>
  <div class="personal">  
    <h3>My Personal appointments </h3>
    <%if Appointment.where(:user_id => current_user.id).count != 0 %> 
      <% @user_appointments.each do |appointment| %>
    <section class="box-personal">
      <p class="TitleOfAppointment"><span>Title of Appointment/Event:</span> <%= appointment.title %></p>
      <p><span>Location:</span> <%= appointment.location %> </p>
      <p><span>Description:</span> <%= appointment.description %></p>
      <p><span>Time:</span> <%= appointment.time %> </p>
        <%if appointment.time < DateTime.now %>
      <p style="color:red;">this appointment has passed</p>
        <% end %>
      <%= link_to "Edit", edit_appointment_path(appointment), class: "edit" %>
      <%= link_to 'Destroy', appointment_path(appointment),
      method: :delete, data: { confirm: 'Are you sure?' }, class: "destroy" %>
    </section>
      <% end %>
    <% else %>
     <p>You have not created any appointments yet </p>
   </section>
    <% end %>
  </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="flash-message-error"><p class="error"><%= flash[:error] %></p>
  <p class="error"><%= flash[:emailerror] %></p>
</div>
<h2 class="title">Create a new appointment</h2>
<div class="container new_form">
  <div class="row">
    <div class="form-errors">
      <% if @appointment.errors.any? %>
      <p><%= pluralize(@appointment.errors.count, "error") %> prohibited this post from being saved:</p>
      <ul class="error-msgs">
        <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
      <% end %>
    <div class="create-new">
      <%= render partial: 'form_new' %>
    </div>
  </div>
</div>